### ISSUE TITLE
Twig in Javascript code

### ISSUE THREAD

**Issue by WilliamVercken** [Anomareh/PHP-Twig.tmbundle#48]
Hi !

When I'm using Twig in a Javascript code, there are some issues like this : 
![image](https://cloud.githubusercontent.com/assets/1272792/6372125/fb1d4b1a-bd01-11e4-87c4-12049225cec5.png)

I'm on Sublime Text 2

**Comment by Anomareh** [comment]
This should be fixed now, thanks for the report.

**Comment by bgatellier** [comment]
Hi,

I'm still facing this issue, using ST3 (3114) on Windows 10. I don't know if it's related or not, but I'm using the theme _[Boxy Ocean](https://github.com/oivva/boxy#boxy-ocean)_.

![phptwig](https://cloud.githubusercontent.com/assets/1890804/17290980/96b19556-57e1-11e6-947e-524fc287ed5f.png)

Anyway, thx for this package :)
